# Generated by Django 5.2.5 on 2025-10-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionData",
            fields=[
                ("subscription", models.JSONField()),
                (
                    "device_id",
                    models.CharField(max_length=400, primary_key=True, serialize=False),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkin.student",
                    ),
                ),
            ],
        ),
    ]
