# Generated by Django 5.2.7 on 2026-04-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionData',
            fields=[
                ('subscription', models.JSONField()),
                ('device_id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.student')),
            ],
        ),
    ]
