# Generated by Django 5.2.5 on 2025-09-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription", models.JSONField()),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkin.student",
                    ),
                ),
            ],
        ),
    ]
