# Generated by Django 5.2.5 on 2025-09-07 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
        ('notifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondata',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.student'),
        ),
    ]
