# Generated by Django 5.2.7 on 2026-04-24 11:55

import bitfield.models
import checkin.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeBlockToday',
            fields=[
                ('block', models.CharField(max_length=1, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[A-G]')])),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SeniorPrivilegesBan',
            fields=[
                ('is_for', models.CharField(max_length=45, primary_key=True, serialize=False, validators=[checkin.models.email_or_everyone])),
            ],
        ),
        migrations.CreateModel(
            name='TownHallMeetingToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('free_blocks', bitfield.models.BitField(('A', 'B', 'C', 'D', 'E', 'F', 'G'), default=0)),
                ('name', models.CharField(default='[Unknown]', max_length=30)),
                ('is_senior', models.BooleanField(default=False)),
                ('advisor_request_idx', models.PositiveIntegerField(choices=[(0, 'not_requested'), (1, 'pending'), (2, 'accepted')])),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkin.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorPrivilegeCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=32)),
                ('checked_out', models.BooleanField()),
                ('check_out_date', models.DateTimeField()),
                ('check_in_date', models.DateTimeField(null=True)),
                ('video', models.FileField(blank=True, upload_to='checkin_vids/senior_privileges/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.student')),
            ],
        ),
        migrations.CreateModel(
            name='TownHallCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=32)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.student')),
            ],
        ),
        migrations.CreateModel(
            name='FreePeriodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_block_idx', models.PositiveSmallIntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E'), (5, 'F'), (6, 'G')])),
                ('device_id', models.CharField(max_length=32)),
                ('video', models.FileField(blank=True, upload_to='checkin_vids/free_periods/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_records', to='checkin.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device_id', 'free_block_idx'), name='unique_device_id'), models.UniqueConstraint(fields=('student', 'free_block_idx'), name='unique_student')],
            },
        ),
    ]
