# Generated by Django 5.2.5 on 2025-08-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='not_checked_in_free_blocks',
            new_name='absent_free_blocks',
        ),
    ]
