# Generated by Django 5.2.5 on 2025-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seniorprivilegecheckin",
            name="video",
            field=models.FileField(blank=True, upload_to="checkin_vids/"),
        ),
    ]
