# Generated by Django 5.2.7 on 2026-04-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_townhallcheckin_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='advisor_request_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='advisor_req',
            field=models.PositiveIntegerField(choices=[(0, 'none'), (1, 'pending'), (2, 'accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkin.advisor'),
        ),
    ]
