# Generated by Django 5.2.5 on 2025-10-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0002_alter_seniorprivilegecheckin_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="seniorprivilegecheckin",
            name="device_id",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="freeperiodcheckin",
            constraint=models.UniqueConstraint(
                fields=("student", "free_block_idx"), name="unique_student"
            ),
        ),
    ]
