# Generated by Django 5.2.5 on 2025-08-24 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_rename_not_checked_in_free_blocks_student_absent_free_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfreeblock',
            name='label',
            field=models.CharField(max_length=1, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[A-G]*')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='absent_free_blocks',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator('[A-G]*')]),
        ),
    ]
