# Generated by Django 5.2.5 on 2025-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_alter_customfreeblock_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='[Unknown]', max_length=100),
        ),
    ]
