# Generated by Django 5.2.7 on 2026-04-29 21:05

import checkin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_student_advisor_request_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownHallMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('code', models.CharField(default=checkin.models.generate_town_hall_code, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TownHallMeetingToday',
        ),
    ]
