# Generated by Django 5.2.5 on 2025-09-22 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_student_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('device_id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('free_blocks', models.CharField(blank=True, default='', max_length=8, validators=[django.core.validators.RegexValidator('[A-G]*')])),
            ],
        ),
    ]
