# Generated by Django 5.2.5 on 2025-10-09 11:25

import bitfield.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_alter_freeperiodcheckin_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_manual_reset', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BgExecutorMsgs',
        ),
        migrations.RemoveField(
            model_name='freeperiodcheckin',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seniorprivilegecheckin',
            name='date',
        ),
        migrations.AddField(
            model_name='seniorprivilegecheckin',
            name='check_in_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='seniorprivilegecheckin',
            name='check_out_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='free_blocks',
            field=bitfield.models.BitField(('A', 'B', 'C', 'D', 'E', 'F', 'G'), default=0),
        ),
    ]
