# Generated by Django 5.2.5 on 2025-09-23 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_checkinrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBlockToday',
            fields=[
                ('block', models.CharField(max_length=1, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[A-G]')])),
                ('time', models.TimeField()),
            ],
        ),
    ]
