# Generated by Django 5.2.5 on 2025-09-04 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='absent_free_blocks',
        ),
        migrations.AddField(
            model_name='student',
            name='checked_in_blocks',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator('[A-G]*')]),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='[Unknown]', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='free_blocks',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator('[A-G]*')]),
        ),
    ]
