# Generated by Django 5.2.7 on 2026-04-30 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_townhallmeeting_delete_townhallmeetingtoday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='townhallcheckin',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='townhallcheckin',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkin.townhallmeeting'),
        ),
    ]
