# Generated by Django 5.2.5 on 2025-09-04 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_remove_student_absent_free_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfreeblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfreeblock',
            name='label',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('[A-G]*')]),
        ),
    ]
