# Generated by Django 5.2.7 on 2026-04-30 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_remove_townhallcheckin_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townhallcheckin',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.townhallmeeting'),
        ),
    ]
