# Generated by Django 5.2.7 on 2025-10-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_persistentstate_delete_bgexecutormsgs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorPrivilegesAllowedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PersistentState',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_sp',
        ),
        migrations.AddField(
            model_name='student',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='[Unknown]', max_length=30),
        ),
    ]
