# Generated by Django 5.2.7 on 2026-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_alter_townhallcheckin_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='townhallmeeting',
            name='title',
            field=models.CharField(default='Unnamed Town Hall Meeting', max_length=100),
        ),
    ]
