# Generated by Django 5.2.5 on 2025-10-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_backgroundexecutorrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_checkin_vids',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CheckInVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='checkin_vids/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='checkin.student')),
            ],
        ),
    ]
