# Generated by Django 5.2.5 on 2025-10-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0007_checkinvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="senior_privilege_status",
            field=models.CharField(
                choices=[
                    ("na", "not_available"),
                    ("ia", "available"),
                    ("co", "checked_out"),
                    ("ci", "checked_in"),
                ],
                default="na",
                max_length=2,
            ),
        ),
    ]
