# Generated by Django 5.2.7 on 2025-10-12 14:12

import checkin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_seniorprivilegesban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seniorprivilegesban',
            name='id',
        ),
        migrations.AlterField(
            model_name='seniorprivilegesban',
            name='is_for',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, validators=[checkin.models.email_or_everyone]),
        ),
    ]
