# Generated by Django 5.2.5 on 2025-10-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_student_senior_privilege_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgExecutorMsgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_manual_reset', models.BooleanField(default=False)),
                ('seniors_grad_year', models.PositiveSmallIntegerField(default=2024)),
            ],
        ),
        migrations.DeleteModel(
            name='BackgroundExecutorRequests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='senior_privilege_status',
        ),
        migrations.AddField(
            model_name='student',
            name='sp_status',
            field=models.CharField(choices=[('na', 'Not Available'), ('ia', 'Available'), ('co', 'Checked Out'), ('ci', 'Checked In')], default='na', max_length=2),
        ),
    ]
