# Generated by Django 5.2.7 on 2025-10-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_remove_seniorprivilegesban_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorprivilegecheckin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.student'),
        ),
    ]
