# Generated by Django 5.2.7 on 2025-10-13 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0009_alter_seniorprivilegecheckin_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freeblocktoday",
            name="time",
        ),
        migrations.AddField(
            model_name="freeblocktoday",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 13, 18, 54, 59, 583908)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="freeblocktoday",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 13, 18, 55, 7, 962381)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="seniorprivilegecheckin",
            name="check_out_date",
            field=models.DateTimeField(),
        ),
    ]
