# Generated by Django 5.2.7 on 2026-02-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0010_remove_freeblocktoday_time_freeblocktoday_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(default='[Unknown]', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TownHallMeetingToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TownHallCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=32)),
                ('video', models.FileField(blank=True, upload_to='checkin_vids/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.student')),
            ],
        ),
    ]
