# Generated by Django 5.2.5 on 2025-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0010_checkinrecord_sp_checkin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgexecutormsgs',
            name='seniors_grad_year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
    ]
