# Generated by Django 5.2.5 on 2025-10-06 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0011_alter_bgexecutormsgs_seniors_grad_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkinvideo',
            name='unique_checkin_vid',
        ),
        migrations.RemoveField(
            model_name='checkinvideo',
            name='block',
        ),
        migrations.AddField(
            model_name='checkinvideo',
            name='is_for',
            field=models.CharField(default='A', max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^([A-G]|SP)$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='sp_status',
            field=models.CharField(choices=[('na', 'Not Available'), ('ia', 'Available'), ('co', 'Checked Out')], default='na', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='checkinvideo',
            constraint=models.UniqueConstraint(fields=('student', 'is_for'), name='unique_checkin_vid'),
        ),
    ]
