# Generated by Django 5.2.5 on 2025-08-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackbaudToken',
            fields=[
                ('token_type', models.CharField(max_length=40)),
                ('access_token', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=200)),
                ('expires_at', models.PositiveIntegerField()),
            ],
        ),
    ]
