# Generated by Django 5.2.5 on 2025-09-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackbaudtoken',
            name='access_token',
            field=models.CharField(max_length=1300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blackbaudtoken',
            name='refresh_token',
            field=models.CharField(max_length=100),
        ),
    ]
