# Generated by Django 5.2.5 on 2025-09-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_blackbaudtoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackbaudtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blackbaudtoken',
            name='access_token',
            field=models.CharField(max_length=1300),
        ),
    ]
