/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeoLocationTestRouteImport } from './routes/GeoLocationTest'
import { Route as CheckInPageRouteImport } from './routes/CheckInPage'
import { Route as AdvisorDashboardRouteImport } from './routes/AdvisorDashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginDefaultRouteImport } from './routes/login/Default'
import { Route as LoginAdvisorSignupRouteImport } from './routes/login/AdvisorSignup'
import { Route as LoginAdvisorLoginRouteImport } from './routes/login/AdvisorLogin'
import { Route as LoginAdminLoginRouteImport } from './routes/login/AdminLogin'

const WelcomeLazyRouteImport = createFileRoute('/Welcome')()
const KioskPageLazyRouteImport = createFileRoute('/KioskPage')()
const AdminLazyRouteImport = createFileRoute('/Admin')()

const WelcomeLazyRoute = WelcomeLazyRouteImport.update({
  id: '/Welcome',
  path: '/Welcome',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Welcome.lazy').then((d) => d.Route))
const KioskPageLazyRoute = KioskPageLazyRouteImport.update({
  id: '/KioskPage',
  path: '/KioskPage',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/KioskPage.lazy').then((d) => d.Route))
const AdminLazyRoute = AdminLazyRouteImport.update({
  id: '/Admin',
  path: '/Admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Admin.lazy').then((d) => d.Route))
const GeoLocationTestRoute = GeoLocationTestRouteImport.update({
  id: '/GeoLocationTest',
  path: '/GeoLocationTest',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInPageRoute = CheckInPageRouteImport.update({
  id: '/CheckInPage',
  path: '/CheckInPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorDashboardRoute = AdvisorDashboardRouteImport.update({
  id: '/AdvisorDashboard',
  path: '/AdvisorDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDefaultRoute = LoginDefaultRouteImport.update({
  id: '/login/Default',
  path: '/login/Default',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdvisorSignupRoute = LoginAdvisorSignupRouteImport.update({
  id: '/login/AdvisorSignup',
  path: '/login/AdvisorSignup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdvisorLoginRoute = LoginAdvisorLoginRouteImport.update({
  id: '/login/AdvisorLogin',
  path: '/login/AdvisorLogin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminLoginRoute = LoginAdminLoginRouteImport.update({
  id: '/login/AdminLogin',
  path: '/login/AdminLogin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AdvisorDashboard': typeof AdvisorDashboardRoute
  '/CheckInPage': typeof CheckInPageRoute
  '/GeoLocationTest': typeof GeoLocationTestRoute
  '/Admin': typeof AdminLazyRoute
  '/KioskPage': typeof KioskPageLazyRoute
  '/Welcome': typeof WelcomeLazyRoute
  '/login/AdminLogin': typeof LoginAdminLoginRoute
  '/login/AdvisorLogin': typeof LoginAdvisorLoginRoute
  '/login/AdvisorSignup': typeof LoginAdvisorSignupRoute
  '/login/Default': typeof LoginDefaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AdvisorDashboard': typeof AdvisorDashboardRoute
  '/CheckInPage': typeof CheckInPageRoute
  '/GeoLocationTest': typeof GeoLocationTestRoute
  '/Admin': typeof AdminLazyRoute
  '/KioskPage': typeof KioskPageLazyRoute
  '/Welcome': typeof WelcomeLazyRoute
  '/login/AdminLogin': typeof LoginAdminLoginRoute
  '/login/AdvisorLogin': typeof LoginAdvisorLoginRoute
  '/login/AdvisorSignup': typeof LoginAdvisorSignupRoute
  '/login/Default': typeof LoginDefaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AdvisorDashboard': typeof AdvisorDashboardRoute
  '/CheckInPage': typeof CheckInPageRoute
  '/GeoLocationTest': typeof GeoLocationTestRoute
  '/Admin': typeof AdminLazyRoute
  '/KioskPage': typeof KioskPageLazyRoute
  '/Welcome': typeof WelcomeLazyRoute
  '/login/AdminLogin': typeof LoginAdminLoginRoute
  '/login/AdvisorLogin': typeof LoginAdvisorLoginRoute
  '/login/AdvisorSignup': typeof LoginAdvisorSignupRoute
  '/login/Default': typeof LoginDefaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AdvisorDashboard'
    | '/CheckInPage'
    | '/GeoLocationTest'
    | '/Admin'
    | '/KioskPage'
    | '/Welcome'
    | '/login/AdminLogin'
    | '/login/AdvisorLogin'
    | '/login/AdvisorSignup'
    | '/login/Default'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AdvisorDashboard'
    | '/CheckInPage'
    | '/GeoLocationTest'
    | '/Admin'
    | '/KioskPage'
    | '/Welcome'
    | '/login/AdminLogin'
    | '/login/AdvisorLogin'
    | '/login/AdvisorSignup'
    | '/login/Default'
  id:
    | '__root__'
    | '/'
    | '/AdvisorDashboard'
    | '/CheckInPage'
    | '/GeoLocationTest'
    | '/Admin'
    | '/KioskPage'
    | '/Welcome'
    | '/login/AdminLogin'
    | '/login/AdvisorLogin'
    | '/login/AdvisorSignup'
    | '/login/Default'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorDashboardRoute: typeof AdvisorDashboardRoute
  CheckInPageRoute: typeof CheckInPageRoute
  GeoLocationTestRoute: typeof GeoLocationTestRoute
  AdminLazyRoute: typeof AdminLazyRoute
  KioskPageLazyRoute: typeof KioskPageLazyRoute
  WelcomeLazyRoute: typeof WelcomeLazyRoute
  LoginAdminLoginRoute: typeof LoginAdminLoginRoute
  LoginAdvisorLoginRoute: typeof LoginAdvisorLoginRoute
  LoginAdvisorSignupRoute: typeof LoginAdvisorSignupRoute
  LoginDefaultRoute: typeof LoginDefaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Welcome': {
      id: '/Welcome'
      path: '/Welcome'
      fullPath: '/Welcome'
      preLoaderRoute: typeof WelcomeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/KioskPage': {
      id: '/KioskPage'
      path: '/KioskPage'
      fullPath: '/KioskPage'
      preLoaderRoute: typeof KioskPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin': {
      id: '/Admin'
      path: '/Admin'
      fullPath: '/Admin'
      preLoaderRoute: typeof AdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/GeoLocationTest': {
      id: '/GeoLocationTest'
      path: '/GeoLocationTest'
      fullPath: '/GeoLocationTest'
      preLoaderRoute: typeof GeoLocationTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CheckInPage': {
      id: '/CheckInPage'
      path: '/CheckInPage'
      fullPath: '/CheckInPage'
      preLoaderRoute: typeof CheckInPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdvisorDashboard': {
      id: '/AdvisorDashboard'
      path: '/AdvisorDashboard'
      fullPath: '/AdvisorDashboard'
      preLoaderRoute: typeof AdvisorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/Default': {
      id: '/login/Default'
      path: '/login/Default'
      fullPath: '/login/Default'
      preLoaderRoute: typeof LoginDefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/AdvisorSignup': {
      id: '/login/AdvisorSignup'
      path: '/login/AdvisorSignup'
      fullPath: '/login/AdvisorSignup'
      preLoaderRoute: typeof LoginAdvisorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/AdvisorLogin': {
      id: '/login/AdvisorLogin'
      path: '/login/AdvisorLogin'
      fullPath: '/login/AdvisorLogin'
      preLoaderRoute: typeof LoginAdvisorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/AdminLogin': {
      id: '/login/AdminLogin'
      path: '/login/AdminLogin'
      fullPath: '/login/AdminLogin'
      preLoaderRoute: typeof LoginAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorDashboardRoute: AdvisorDashboardRoute,
  CheckInPageRoute: CheckInPageRoute,
  GeoLocationTestRoute: GeoLocationTestRoute,
  AdminLazyRoute: AdminLazyRoute,
  KioskPageLazyRoute: KioskPageLazyRoute,
  WelcomeLazyRoute: WelcomeLazyRoute,
  LoginAdminLoginRoute: LoginAdminLoginRoute,
  LoginAdvisorLoginRoute: LoginAdvisorLoginRoute,
  LoginAdvisorSignupRoute: LoginAdvisorSignupRoute,
  LoginDefaultRoute: LoginDefaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
